# # Network Config
- keyboard_config:
  - write_in:
    - /etc/default/keyboard
    - |
      XKBMODEL="pc105"
      XKBLAYOUT="$${layout}"
      XKBVARIANT=""
      XKBOPTIONS=""
  - apt-get_in: install console-setup console-data
